import React, { useEffect, useState } from "react";
import { api } from "@/lib/api";
import { toast } from "sonner";
import { CardSkeleton } from "@/components/SkeletonLoader";
import { GuidanceCompass } from "@/components/GuidanceCompass";
import { uploadToCloudinary } from "@/lib/cloudinary";
import { useAuth } from "@/context/AuthContext";
import { useI18n } from "@/context/I18nContext";
import "leaflet/dist/leaflet.css";
import L from "leaflet";
import { 
  X, 
  MapPin, 
  Brain, 
  NavigationArrow, 
  CheckCircle, 
  ArrowsClockwise, 
  Play 
} from "@phosphor-icons/react";
import { Skeleton } from "@/components/ui/skeleton";

/** Minimal status pill — no heavy borders */
function StatusPill({ status }) {
  const map = {
    active:      'bg-orange-100 text-orange-700',
    in_progress: 'bg-orange-100 text-orange-700',
    completed:   'bg-green-100 text-green-700',
    planned:     'bg-[var(--bone)] text-[var(--ink-soft)] border border-[var(--border)]',
  };
  return (
    <span className={`inline-block px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wider rounded-sm ${map[status] || map.planned}`}>
      {status}
    </span>
  );
}


function MissionBrief({ text }) {
  if (!text) return <span className="text-[var(--ink-soft)] italic text-xs">Generate a brief to see objective, risks, and actions here.</span>;

  // 🧹 Sanitize: Remove redundant headers often generated by AI
  const cleanText = text.replace(/^(#+\s*)?MISSION BRIEF:.*$/m, "").trim();
  
  const lines = cleanText.split("\n");
  const elements = [];
  let bulletBuffer = [];

  const flushBullets = (key) => {
    if (bulletBuffer.length === 0) return;
    elements.push(
      <ul key={`ul-${key}`} className="space-y-1 my-1">
        {bulletBuffer.map((b, i) => (
          <li key={i} className="flex gap-2 text-xs text-[var(--ink)] leading-snug">
            <span className="mt-0.5 shrink-0 w-1.5 h-1.5 rounded-full bg-[var(--signal-red)] inline-block" />
            <span dangerouslySetInnerHTML={{ __html: b }} />
          </li>
        ))}
      </ul>
    );
    bulletBuffer = [];
  };

  const renderInline = (raw) =>
    raw.replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>").replace(/\*(.+?)\*/g, "<em>$1</em>");

  lines.forEach((line, i) => {
    const trimmed = line.trim();
    if (!trimmed) { flushBullets(i); return; }

    if (trimmed.startsWith("#### ")) {
      flushBullets(i);
      elements.push(
        <div key={i} className="text-[10px] font-black uppercase tracking-widest text-[var(--ink-soft)] mt-4 mb-2">
          {trimmed.replace("#### ", "")}
        </div>
      );
    } else if (trimmed.startsWith("### ")) {
      flushBullets(i);
      elements.push(
        <div key={i} className="text-[11px] font-black uppercase tracking-[0.14em] text-[var(--ink)] border-b-2 border-[var(--border)] pb-2 mb-4 mt-8 first:mt-0">
          {trimmed.replace("### ", "")}
        </div>
      );
    } else if (trimmed.startsWith("* ") || trimmed.startsWith("- ")) {
      bulletBuffer.push(renderInline(trimmed.slice(2)));
    } else {
      flushBullets(i);
      elements.push(
        <p key={i} className="text-[13px] font-medium text-[var(--ink)] leading-[1.6] mb-4 opacity-90"
          dangerouslySetInnerHTML={{ __html: renderInline(trimmed) }} />
      );
    }
  });
  flushBullets("end");

  return <div className="space-y-2">{elements}</div>;
}

const MissionMap = ({ route }) => {
  if (!route || route.length === 0) return null;
  const center = [route[0].lat, route[0].lng];
  const points = route.map(p => [p.lat, p.lng]);

  const tacticalIcon = (index) => L.divIcon({
    className: 'tactical-marker',
    html: `<div style="background-color: ${index === 0 ? '#E63946' : '#1D3557'}; width: 18px; height: 18px; border: 2px solid white; border-radius: 50%; display: flex; align-items: center; justify-content: center; color: white; font-size: 10px; font-weight: 900; box-shadow: 0 0 0 4px rgba(0,0,0,0.1);">${index + 1}</div>`,
    iconSize: [18, 18],
    iconAnchor: [9, 9]
  });

  return (
    <div className="h-[250px] w-full border-2 border-[var(--border)] shadow-[4px_4px_0px_var(--bone-alt)] relative overflow-hidden group mb-4">
      <MapContainer center={center} zoom={12} scrollWheelZoom={false} className="h-full w-full z-0">
        <TileLayer url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" />
        <Polyline positions={points} color="#E63946" weight={3} dashArray="10, 10" opacity={0.6} />
        {route.map((p, i) => (
          <Marker key={i} position={[p.lat, p.lng]} icon={tacticalIcon(i)}>
            <Popup><div className="font-black text-[10px]">STOP {i+1}</div></Popup>
          </Marker>
        ))}
      </MapContainer>
    </div>
  );
};

export default function MissionsPage() {
  const { user } = useAuth();
  const { t } = useI18n();
  const [missions, setMissions] = useState([]);
  const [selected, setSelected] = useState(null);
  const [proofUrls, setProofUrls] = useState([]);
  const [uploadingProof, setUploadingProof] = useState(false);
  const [loading, setLoading] = useState(true);
  const [activeCompass, setActiveCompass] = useState(null); // stores mission id
  const [briefs, setBriefs] = useState({});
  const [briefLoading, setBriefLoading] = useState(null);
  const [routeLoading, setRouteLoading] = useState(null);
  const [focusedMissionId, setFocusedMissionId] = useState(null);
  const [completionNotes, setCompletionNotes] = useState(""); // #19: user-entered notes

  const selectedMission = missions.find((mission) => mission.id === focusedMissionId || mission.id === activeCompass) || null;

  const formatDistance = (value) => {
    if (typeof value !== "number" || Number.isNaN(value)) return null;
    if (value >= 1000) return `${(value / 1000).toFixed(1)} km`;
    return `${Math.round(value)} m`;
  };

  const getRoutePreviewStops = (mission) => {
    if (!mission?.route?.length) return [];

    return mission.route.map((point, index) => ({
      label: `Stop ${index + 1}`,
      lat: typeof point?.lat === "number" ? point.lat.toFixed(4) : "--",
      lng: typeof point?.lng === "number" ? point.lng.toFixed(4) : "--",
      distance: formatDistance(point?.distance),
    }));
  };

  const load = async () => {
    setLoading(true);
    try {
      const r = await api.get("/missions");
      setMissions(r.data);
    } finally {
      setLoading(false);
    }
  };
  useEffect(() => { load(); }, []);

  const handleProofFiles = async (files) => {
    if (!files || files.length === 0) return;
    setUploadingProof(true);
    const t = toast.loading("Uploading proof...");
    try {
      const uploads = await Promise.all(
        Array.from(files).map((file) => uploadToCloudinary(file))
      );
      setProofUrls((prev) => [...prev, ...uploads]);
      toast.success("Proof uploaded", { id: t });
    } catch {
      toast.error("Upload failed", { id: t });
    } finally {
      setUploadingProof(false);
    }
  };

  const removeProof = (url) => {
    setProofUrls((prev) => prev.filter((u) => u !== url));
  };

  const complete = async (m) => {
    try {
      await api.post(`/missions/${m.id}/complete`, {
        proof_urls: proofUrls,
        completion_notes: completionNotes.trim() || "Completed via console",
      });
      toast.success("Mission completed. Trust scores updated.");
      setSelected(null); setProofUrls([]); setCompletionNotes("");
      load();
    } catch (e) { toast.error(e?.response?.data?.detail || "Complete failed. Admin or volunteer role required."); } // #6: show real error
  };

  const acceptMission = async (m) => {
    const t = toast.loading("Starting mission...");
    try {
      await api.post(`/missions/${m.id}/accept`);
      toast.success("Mission active", { id: t });
      load();
    } catch (e) {
      toast.error(e?.response?.data?.detail || "Unable to start", { id: t });
    }
  };

  const optimizeRoute = async (m) => {
    const t = toast.loading("Optimizing route...");
    setRouteLoading(m.id);
    try {
      const r = await api.post(`/missions/${m.id}/optimize-route`);
      setMissions((prev) => prev.map((mission) => (
        mission.id === m.id
          ? { ...mission, route: r.data.route }
          : mission
      )));
      toast.success("Route optimized", { id: t });
    } catch {
      toast.error("Route optimization failed", { id: t });
    } finally {
      setRouteLoading(null);
    }
  };

  const loadBrief = async (m) => {
    setFocusedMissionId(m.id);
    setBriefLoading(m.id);
    try {
      const r = await api.post(`/missions/${m.id}/brief`, { refresh: false });
      setBriefs((prev) => ({ ...prev, [m.id]: r.data.brief }));
    } catch {
      toast.error("Brief generation failed");
    } finally {
      setBriefLoading(null);
    }
  };

  return (
    <>
      <div className="p-6 md:p-10 max-w-full min-h-screen bg-[var(--bone)]" data-testid="missions-page">

        {/* Page Header */}
        <div className="mb-8 pb-6 border-b border-[var(--border)]">
          <div className="flex items-center gap-2 mb-1">
            <span className="w-1.5 h-1.5 rounded-full bg-green-500" />
            <span className="text-[10px] font-semibold uppercase tracking-[0.18em] text-[var(--ink-soft)]">Field Operations</span>
          </div>
          <h1 className="font-heading text-3xl md:text-4xl font-bold tracking-tight text-[var(--ink)] m-0">Missions</h1>
        </div>

        {missions.length === 0 && !loading ? (
          <div className="py-20 text-center">
            <p className="text-sm text-[var(--ink-soft)] font-medium">No operations dispatched.</p>
          </div>
        ) : (
          <div className="grid md:grid-cols-2 gap-3">
            {loading ? (
              [1, 2, 3, 4].map(i => (
                <div key={i} className="tc-card p-6 min-h-[220px] flex flex-col justify-between animate-pulse">
                  <div className="flex justify-between">
                    <Skeleton className="h-3 w-32" />
                    <Skeleton className="h-4 w-12" />
                  </div>
                  <Skeleton className="h-6 w-3/4" />
                  <div className="space-y-2 mt-4">
                    <Skeleton className="h-2 w-full" />
                    <Skeleton className="h-2 w-full" />
                  </div>
                  <div className="flex gap-2 mt-4">
                    <Skeleton className="h-8 w-16" />
                    <Skeleton className="h-8 w-16" />
                    <Skeleton className="h-8 w-16" />
                  </div>
                </div>
              ))
            ) : (
              missions.map((m) => (
                <div
                  key={m.id}
                  className={`bg-[var(--bone-alt)] border border-[var(--border)] p-5 hover:border-[var(--ink-soft)] transition-all cursor-pointer group ${
                    m.id === focusedMissionId ? "border-[var(--ink)] shadow-sm" : ""
                  }`}
                  onClick={() => setFocusedMissionId(m.id)}
                >
                  {/* Top row: ID + status */}
                  <div className="flex items-start justify-between mb-3">
                    <span className="font-mono text-[10px] text-[var(--ink-soft)] truncate max-w-[200px]">{m.id}</span>
                    <StatusPill status={m.status} />
                  </div>

                  {/* Title */}
                  <h3 className="text-base font-semibold text-[var(--ink)] leading-snug mb-4 group-hover:text-[var(--signal-red)] transition-colors">
                    {/* #14: prefer title over long description paragraph */}
                  {m.title || m.description || "Untitled Operation"}
                  </h3>

                  {/* Meta row */}
                  <div className="flex items-center gap-5 text-[11px] text-[var(--ink-soft)] border-t border-[var(--border)] pt-3 mb-4">
                    <span><span className="font-semibold text-[var(--ink)]">{(m.route || []).length}</span> stops</span>
                    {/* #15: field is volunteer_ids[], not assigned_to string */}
                    <span className="truncate">{m.volunteer_ids?.length > 0 ? `${m.volunteer_ids.length} assigned` : m.assigned_to || "Unassigned"}</span>
                    {(briefs[m.id] || m.brief) && (
                      <span className="ml-auto text-[10px] text-green-700 font-semibold">Brief ready</span>
                    )}
                  </div>

                  {/* Actions */}
                  {m.status !== "completed" && (
                    <div className="flex flex-wrap gap-2">
                      {(user?.role === "volunteer" && m.status !== "in_progress") && (
                        <button
                          className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-[var(--ink)] text-[var(--bone)] text-[11px] font-semibold hover:opacity-80 transition-opacity"
                          onClick={(e) => { e.stopPropagation(); acceptMission(m); }}
                        >
                          <Play weight="fill" size={12} /> Start
                        </button>
                      )}
                      <button
                        className="inline-flex items-center gap-1.5 px-3 py-1.5 border border-[var(--border)] bg-white text-[var(--ink)] text-[11px] font-semibold hover:border-[var(--ink-soft)] transition-colors"
                        onClick={(e) => { e.stopPropagation(); setSelected(m); }}
                      >
                        <CheckCircle weight="regular" size={13} /> Complete
                      </button>
                      <button
                        className="inline-flex items-center gap-1.5 px-3 py-1.5 border border-[var(--border)] bg-white text-[var(--ink)] text-[11px] font-semibold hover:border-[var(--ink-soft)] transition-colors"
                        onClick={(e) => { e.stopPropagation(); setFocusedMissionId(m.id); }}
                      >
                        <Brain weight="regular" size={13} /> Brief
                      </button>
                      <button
                        className={`inline-flex items-center gap-1.5 px-3 py-1.5 border text-[11px] font-semibold transition-colors ${
                          activeCompass === m.id
                          ? 'border-[var(--signal-red)] bg-[var(--signal-red)] text-white'
                          : 'border-[var(--border)] bg-white text-[var(--ink)] hover:border-[var(--ink-soft)]'
                        }`}
                        onClick={(e) => { e.stopPropagation(); setActiveCompass(activeCompass === m.id ? null : m.id); }}
                      >
                        <NavigationArrow weight="regular" size={13} /> {activeCompass === m.id ? 'Stop' : 'Nav'}
                      </button>
                      <button
                        className="inline-flex items-center gap-1.5 px-3 py-1.5 border border-[var(--border)] bg-white text-[var(--ink)] text-[11px] font-semibold hover:border-[var(--ink-soft)] transition-colors disabled:opacity-40"
                        onClick={(e) => { e.stopPropagation(); optimizeRoute(m); }}
                        disabled={routeLoading === m.id}
                      >
                        <ArrowsClockwise weight="regular" size={13} /> {routeLoading === m.id ? "..." : "Route"}
                      </button>
                    </div>
                  )}

                  {activeCompass === m.id && m.route && m.route.length > 0 && (
                    <div className="mt-4 pt-4 border-t border-[var(--border)]">
                      <GuidanceCompass targetLat={m.route[0].lat} targetLng={m.route[0].lng} />
                    </div>
                  )}
                </div>
              ))
            )}
          </div>
        )}
      </div>

      {selectedMission && (
        <div className="fixed inset-0 top-0 left-0 w-screen h-screen z-[99999] bg-[var(--bone)] flex flex-col !m-0 !p-0" onClick={() => setFocusedMissionId(null)}>
          <div 
            className="w-full h-full flex flex-col overflow-hidden" 
            onClick={(e) => e.stopPropagation()}
          >
            {/* Modal Header */}
            <div className="px-5 py-4 border-b border-[var(--border)] bg-[var(--bone-alt)] flex items-center justify-between shrink-0">
              <div className="space-y-0.5 overflow-hidden">
                <div className="flex items-center gap-2">
                  <StatusPill status={selectedMission.status} />
                  <span className="text-[10px] text-[var(--ink-soft)] font-mono truncate">{selectedMission.id}</span>
                </div>
                <h2 className="font-heading text-lg md:text-2xl font-bold tracking-tight text-[var(--ink)] leading-tight m-0 truncate">
                  {/* #26: use title/description, not UUID-derived string */}
                  {selectedMission.title || selectedMission.description?.slice(0, 60) || selectedMission.id?.slice(0, 8).toUpperCase()}
                </h2>
              </div>
              <button
                onClick={() => setFocusedMissionId(null)}
                className="w-8 h-8 flex items-center justify-center border border-[var(--border)] bg-white hover:bg-[var(--bone-alt)] text-[var(--ink-soft)] hover:text-[var(--ink)] transition-colors shrink-0 ml-4"
              >
                <X size={16} weight="bold" />
              </button>
            </div>

            <div className="flex-1 overflow-y-auto p-5 md:p-8 space-y-8 pb-28">
              {/* Map */}
              <div>
                <p className="text-[10px] font-semibold uppercase tracking-[0.15em] text-[var(--ink-soft)] mb-3 flex items-center gap-1.5"><MapPin size={12} /> {t('route')}</p>
                <MissionMap route={selectedMission.route} />
              </div>

              <div className="grid md:grid-cols-2 gap-8 items-start">
                {/* Brief */}
                <div>
                  <p className="text-[10px] font-semibold uppercase tracking-[0.15em] text-[var(--ink-soft)] mb-3 flex items-center gap-1.5"><Brain size={12} /> {t('mission_brief')}</p>
                  <div className="bg-[var(--bone-alt)] border border-[var(--border)] p-5 text-sm leading-relaxed">
                    <MissionBrief text={briefs[selectedMission.id] || selectedMission.brief} />
                  </div>
                </div>

                {/* Route stops */}
                <div>
                  <p className="text-[10px] font-semibold uppercase tracking-[0.15em] text-[var(--ink-soft)] mb-3 flex items-center gap-1.5"><NavigationArrow size={12} /> {t('logistics')}</p>
                  <div className="space-y-2">
                    {selectedMission.route?.length > 0 ? (
                      getRoutePreviewStops(selectedMission).map((stop, index) => (
                        <div key={`stop-${index}`} className="flex items-center gap-3 py-2.5 border-b border-[var(--border)] last:border-b-0">
                          <span className="w-5 h-5 rounded-full border border-[var(--border)] bg-[var(--bone-alt)] flex items-center justify-center text-[10px] font-semibold shrink-0">{index + 1}</span>
                          <div className="flex-1 min-w-0">
                            <div className="text-xs font-medium text-[var(--ink)] font-mono">{stop.lat}, {stop.lng}</div>
                            {stop.distance && <div className="text-[10px] text-[var(--ink-soft)]">{stop.distance}</div>}
                          </div>
                        </div>
                      ))
                    ) : (
                      <p className="text-xs text-[var(--ink-soft)] py-4">{t('no_route_generated')}</p>
                    )}
                  </div>
                </div>
              </div>
            </div>

            {/* Action Bar */}
            <div className="px-5 py-4 border-t border-[var(--border)] bg-[var(--bone-alt)] flex flex-wrap gap-2 shrink-0">
              {selectedMission.status !== "completed" ? (
                <>
                  <button
                    className="inline-flex items-center gap-2 px-4 py-2 bg-[var(--ink)] text-[var(--bone)] text-[11px] font-semibold hover:opacity-80 transition-opacity"
                    onClick={() => setSelected(selectedMission)}
                  >
                    <CheckCircle weight="regular" size={14} /> {t('mark_complete')}
                  </button>
                  {user?.role === "volunteer" && selectedMission.status !== "in_progress" && (
                    <button
                      className="inline-flex items-center gap-2 px-4 py-2 bg-green-700 text-white text-[11px] font-semibold hover:opacity-80 transition-opacity"
                      onClick={() => acceptMission(selectedMission)}
                    >
                      <Play weight="fill" size={13} /> {t('start_mission')}
                    </button>
                  )}
                  <button
                    className="inline-flex items-center gap-2 px-4 py-2 border border-[var(--border)] bg-white text-[var(--ink)] text-[11px] font-semibold hover:border-[var(--ink-soft)] transition-colors disabled:opacity-40"
                    onClick={() => loadBrief(selectedMission)}
                    disabled={briefLoading === selectedMission.id}
                  >
                    <Brain weight="regular" size={14} /> {briefLoading === selectedMission.id ? t('loading') : t('sync_brief')}
                  </button>
                  <button
                    className="inline-flex items-center gap-2 px-4 py-2 border border-[var(--border)] bg-white text-[var(--ink)] text-[11px] font-semibold hover:border-[var(--ink-soft)] transition-colors disabled:opacity-40"
                    onClick={() => optimizeRoute(selectedMission)}
                    disabled={routeLoading === selectedMission.id}
                  >
                    <ArrowsClockwise weight="regular" size={14} /> {routeLoading === selectedMission.id ? t('routing') : t('optimize_route')}
                  </button>
                </>
              ) : (
                <div className="flex items-center gap-2 text-green-700 text-[11px] font-semibold py-1">
                  <CheckCircle weight="fill" size={16} /> {t('operation_complete')}
                </div>
              )}
            </div>
          </div>
        </div>
      )}

      {selected && (
        <div className="fixed inset-0 bg-black/30 flex items-end md:items-center justify-center p-0 md:p-6 z-[10000]" onClick={() => setSelected(null)}>
          <div
            onClick={(e) => e.stopPropagation()}
            className="bg-[var(--bone)] border border-[var(--border)] w-full md:max-w-md md:w-full p-6 space-y-5 shadow-lg"
          >
            <div>
              <h3 className="text-sm font-semibold text-[var(--ink)] mb-0.5">Mark as Complete</h3>
              <p className="text-xs text-[var(--ink-soft)]">Upload at least one photo as proof of completion.</p>
            </div>
            <div>
              <label className="block text-[11px] font-semibold text-[var(--ink-soft)] uppercase tracking-wider mb-1.5">Photos</label>
              <input
                type="file"
                className="w-full text-xs text-[var(--ink)] file:mr-3 file:py-1.5 file:px-3 file:border file:border-[var(--border)] file:text-xs file:font-medium file:bg-[var(--bone-alt)] file:text-[var(--ink)] hover:file:bg-white"
                accept="image/*" multiple
                onChange={(e) => handleProofFiles(e.target.files)}
                disabled={uploadingProof}
              />
            </div>
            {proofUrls.length > 0 && (
              <div className="flex flex-wrap gap-2">
                {proofUrls.map((u) => (
                  <div key={u} className="relative group">
                    <img src={u} alt="Proof" className="w-16 h-16 object-cover border border-[var(--border)]" />
                    <button
                      className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center text-white text-lg"
                      onClick={() => removeProof(u)}
                    >×</button>
                  </div>
                ))}
              </div>
            )}
            {/* #19: completion notes field */}
            <div>
              <label className="block text-[11px] font-semibold text-[var(--ink-soft)] uppercase tracking-wider mb-1.5">Completion Notes</label>
              <textarea
                className="w-full tc-textarea text-xs"
                rows={2}
                placeholder="Describe what was done on this mission..."
                value={completionNotes}
                onChange={(e) => setCompletionNotes(e.target.value)}
              />
            </div>
            <div className="flex gap-2 justify-end pt-2 border-t border-[var(--border)]">
              <button
                className="px-4 py-2 text-xs font-semibold text-[var(--ink-soft)] hover:text-[var(--ink)] transition-colors"
                onClick={() => setSelected(null)}
              >Cancel</button>
              <button
                className="px-5 py-2 bg-[var(--ink)] text-[var(--bone)] text-xs font-semibold hover:opacity-80 transition-opacity disabled:opacity-40"
                onClick={() => complete(selected)}
                disabled={uploadingProof} // #32: photo no longer mandatory
              >Confirm</button>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
